### ISSUE TITLE
Sentence "A parrot is a bird" does not return path from shortest_path 

### ISSUE THREAD

**Issue by bwilk7** [vered1986/LexNET#1]
I am not sure if this is one issue or two, feel free to split it into two if you see fit. Both are a result of going through the following code in ```shortest_path```, and never executing the break.

```python
   for i in xrange(min(len(hx), len(hy))):
        if hx[i] is not hy[i]:
            break
````

In the first case, if the sentence like "A parrot is a bird" and *parrot* and *bird* are passed to ```shortest_path```, ```hx``` and ```hy``` will both be ```[is]```. The loop will exit and ```i``` will be 0. Because ```hx[i] == hy[i]``` , ```i``` becomes 1, which causes ```shortest_path``` to return None, as neither ```len(hx)``` or ```len(hy)``` is greater than 1. I believe what should happen in this case is that if both ```hx``` and ```hy``` are the same length and end on the same node, that should become the lowest common head unless I am misinterpreting the logic.

The second example was found with the sentence "Miami has a true tropical climate , specifically tropical monsoon ( K�ppen climate classification Am ) , with hot and humid summers and warm and mostly dry winters ." and passing the words *hot* and *warm* to ```shortest_path```.

In this case ```hx = [has, climate, with, summers]``` and ```hy = [has, climate, with, summers, winters]```. The loop ends when ```i = 3```, and because ```hx[3] == hy[3]```, ```i``` is incresased to 4.  ```len(hy) > 4``` and thus ```lch``` is set to *winters*, which isn't in ```hx```. In, this instance, I think the lowest common head should be *summers*, with ```hx = []``` and ```hy = [winters]```.

**Comment by vered1986** [comment]
Thank you so much for raising these issues and providing detailed examples. I will look into it soon!

**Comment by vered1986** [comment]
Thanks again @bwilk7, and sorry for taking so long to look into it.

Regarding the first issue, this is definitely a bug. I fixed it and did some sanity checks, but I still need to re-create the resource and re-train the entire model to make sure that the results are not worse. For what it's worth, here is the change in the shortest_path function:

```python
def shortest_path(path):
    """ Returns the shortest dependency path from x to y
    :param x: x token
    :param y: y token
    :return: the shortest dependency path from x to y
    """

    # Get the root token and work on it
    if path is None:
        return None

    x_tokens, y_tokens = path
    x_token = x_tokens.root
    y_token = y_tokens.root

    # Get the path from the root to each of the tokens
    hx = heads(x_token)
    hy = heads(y_token)

    # Get the lowest common head

    # There could be several cases. For example, for x = parrot, y = bird:

    # 1. x is the head of y: "[parrot] and other [birds]"
    if hx == [] and x_token in hy:
        hy = hy[:hy.index(x_token)]
        hx = []
        lch = x_token

    # 2. y is the head of x: "[birds] such as [parrots]"
    elif hy == [] and y_token in hx:
        hx = hx[:hx.index(y_token)]
        hy = []
        lch = y_token

    # 3. x and y have no common head - the first head in each list should be the sentence root, so
    # this is possibly a parse error?
    elif hy[0] != hx[0]:
        return None

    # 4. x and y are connected via a direct parent or have the exact same path to the root, as in "[parrot] is a [bird]"
    elif hx == hy:
        lch = hx[-1]
        hx = hy = []

    # 5. x and y have a different parent which is non-direct, as in "[parrot] is a member of the [bird] family".
    # The head is the last item in the common sequence of both head lists.
    else:
        for i in xrange(min(len(hx), len(hy))):
            # Now we've found the common ancestor in i-1
            if hx[i] is not hy[i]:
                break

        if len(hx) > i:
            lch = hx[i-1]
        elif len(hy) > i:
            lch = hy[i-1]
        else:
            return None

        # The path from x to the lowest common head
        hx = hx[i+1:]

        # The path from the lowest common head to y
        hy = hy[i+1:]

    if lch and check_direction(lch, hx, lambda h: h.lefts):
        return None
    hx = hx[::-1]

    if lch and check_direction(lch, hy, lambda h: h.rights):
        return None

    return (x_token, hx, lch, hy, y_token)
```    

And here is a simple code to check all the cases I could think of:

```python
from spacy.en import English
import sys
sys.path.append('corpus')
from parse_wikipedia import *
nlp = English()

for sent in [u'parrot is a bird', u'parrot is a member of the bird family', u'parrot and other birds', u'birds such as parrots']:
	print sent
	doc = nlp(sent)
	print parse_sentence([sent for sent in doc.sents][0], ['parrot', 'bird'])
```
I got the correct paths for all these cases. 

Now, regarding the second issue, I'm pretty sure its discarded because the path direction is inconsistent. The common head "with" is found but it fails on the check_direction function. You get something like:  `with <- summers <- hot` and `summers -> winters <- warm`. I'm also not sure there's no parsing error.

I will close this issue after I make the changes in the repository, just wanted to update that I'm working on it. Thanks again!

**Comment by vered1986** [comment]
I just pushed the bug fix. After implementing the solution I get similar results. Thanks again!
