### ISSUE TITLE
Download wiki dump file

### ISSUE THREAD

**Issue by xcgfth** [vered1986/LexNET#7]
Hello, I wnat to download wiki dump file, but I found there are many files on this [url](https://dumps.wikimedia.org/enwiki/20180701/), which file I should to choose to download?  can you give me the file(s) name? Thank you very much.

**Comment by vered1986** [comment]
Hi, you should download the ["pages-articles-multistream" file](https://dumps.wikimedia.org/enwiki/20180701/enwiki-20180701-pages-articles-multistream.xml.bz2), the full XML dump of articles.

**Comment by xcgfth** [comment]
Okay, I have downloaded it , Thank you very much.

**Comment by zhixiaochuan12** [comment]
@vered1986 You mentioned `pages-articles-multistream` here, but mentioned `enwiki-[some_date]-pages-meta-current.xml.bz2` in your `Detailed Guide`, they are not consistent.

**Comment by vered1986** [comment]
Sorry for the late response. I believe that I used `pages-articles-multistream.xml.bz2` in this work and that I copied the instructions with `enwiki-[some_date]-pages-meta-current.xml.bz2` from a later work. I also think it would probably not make a difference, but I updated the detailed guide.

**Comment by zhixiaochuan12** [comment]
I see. Thanks.
