### ISSUE TITLE
Question about the triplets_file

### ISSUE THREAD

**Issue by TimHsu1998** [vered1986/LexNET#8]
Hello Vered,

Could you upload a copy of your <out_file> from the command "parse_wikipedia.py <wiki_file> <vocabulary_file> <out_file>" ? I would like to see what does it look like so that I can use other types of data. And could you also explain more detail about how can you get wikiPaths.txt?

Thank you!

**Comment by vered1986** [comment]
Hi @TimHsu1998,

Did you see the [detailed guide](https://github.com/vered1986/LexNET/wiki/Detailed-Guide)? I think it may answer some of your questions.

The `out_file` is huge, but each line is as in the following format (tab-separated):

```
cat    animal    such/ADJ/predet/V_Y/NOUN/nsubj/>_include/VERB/ROOT/^_X/NOUN/dobj/<
```

**Comment by TimHsu1998** [comment]
Ya, I see the detail guide, thank you for the response. Maybe I should ask is the paths in resource_prefix + 'Paths.txt' are all the path between nouns and pick only the one which occurs more than five times?

**Comment by vered1986** [comment]
Yes, exactly. In version 2 (not documented in the detailed guide), all you have to do is run [create_resource_from_corpus.sh](https://github.com/vered1986/LexNET/blob/v2/corpus/create_resource_from_corpus.sh) and it takes care of the entire process, from parsing Wikipedia to creating the resource of triplets.
