### ISSUE TITLE
Possibly incorrect paths being generated

### ISSUE THREAD

**Issue by yogarshi** [vered1986/LexNET#9]
Hi Vered, thanks for sharing this code. It has been extremely useful.

I was trying to run some data through [parse_wikipedia.py ](https://github.com/vered1986/LexNET/blob/v2/corpus/parse_wikipedia.py) to generate paths, but some of the paths are not what I expected them to be. Here's an example 

**Sentence** : Anarchism is a political philosophy that advocates self-governed societies based on voluntary institutions .

**Dependency Tree**

```
                      is                                                    
     _________________|_________                                             
    |      |                philosophy                                      
    |      |    ________________|_______________                             
    |      |   |      |                     advocates                       
    |      |   |      |          _______________|_________                   
    |      |   |      |         |                     societies             
    |      |   |      |         |                _________|__________        
    |      |   |      |         |               |                  based    
    |      |   |      |         |               |                    |       
    |      |   |      |         |               |                    on     
    |      |   |      |         |               |                    |       
    |      |   |      |         |            governed           institutions
    |      |   |      |         |        _______|_________           |       
Anarchism  .   a  political    that    self               -      voluntary  
```

**Query words** : _philosophy_, _societies_

**Generated paths**
```
philosophy      society X/NOUN/attr/>_be/VERB/ROOT/^_philosophy/NOUN/attr/<_advocate/VERB/relcl/<_Y/NOUN/dobj/<
philosophy      society political/ADJ/amod/V_X/NOUN/attr/>_be/VERB/ROOT/^_philosophy/NOUN/attr/<_advocate/VERB/relcl/<_Y/NOUN/dobj/<
philosophy      society X/NOUN/attr/>_be/VERB/ROOT/^_philosophy/NOUN/attr/<_advocate/VERB/relcl/<_govern/VERB/amod/V_Y/NOUN/dobj/<
philosophy      society X/NOUN/attr/>_be/VERB/ROOT/^_philosophy/NOUN/attr/<_advocate/VERB/relcl/<_Y/NOUN/dobj/<_base/VERB/acl/V
```

The path from _philosophy_ to _societies_ contains only one intermediate node (_advocates_). The generated paths, however, seem to be going all the way up to the _root_, and then back down to _societies_, and it is unclear if this is the desired behavior.  Shouldn't the first of these paths be

```
philosophy      society X/NOUN/attr/<_advocate/VERB/relcl/<_Y/NOUN/dobj/<
```
(with the satellite links appropriately added to the subsequent paths)

**Comment by vered1986** [comment]
Hi Yogarshi, thanks for catching this! Indeed, this seems like a bug, and this is the path I have in my processed corpus. It seems like it fails to find the lowest common ancestor when it is one of the given words (_philosophy_ in this case), and instead goes up to the root. 

I think these are the required changes:

1. In line [116](https://github.com/vered1986/LexNET/blob/v2/corpus/parse_wikipedia.py#L116), I missed the cases in which x is the head of y but is not the root of the sentence. The condition `hx == []` needs to be removed. (The same thing happens in line [122](https://github.com/vered1986/LexNET/blob/v2/corpus/parse_wikipedia.py#L122) with `hy == []`). 

2. Line [117](https://github.com/vered1986/LexNET/blob/v2/corpus/parse_wikipedia.py#L117) should be changed to `hy = hy[hy.index(x_token)+1:]` - we should only keep the ancestors of y which are not ancestors of x. 

I ran a sanity check with 4 examples in which x/y is the head of y/x and is/isn't the root of the sentences:

```(python)
In [1]: nlp = spacy.load('en')

In [2]: for par in ['Anarchism is a political philosophy that advocates self-governed societies based on voluntary institutions .', 'parrot and other birds', 'birds such as parrots', 'I have birds such as parrots']:
    parsed_par = nlp(unicode(par))
    vocabulary = list({ t.orth_ for t in parsed_par }.union({ t.lemma_ for t in parsed_par }))
    sent = [s for s in parsed_par.sents][0]
    dependency_paths = parse_sentence(sent, vocabulary)
    
    for (x, y), paths in dependency_paths.iteritems():
        for path in paths:
            print('\t'.join([x, y, path]))
```
I got the expected output. For example:

```
philosophy	society	X/NOUN/attr/^_advocate/VERB/relcl/<_Y/NOUN/dobj/<
```

I will need some time to re-run things and see that I didn't create new bugs, but in the meantime you can use these changes. Thanks again!

**Comment by yogarshi** [comment]
Thanks for the quick response. The changes look reasonable to me, and I will incorporate them into my  code, but will leave this open till you get a chance to edit the repo. Thanks again!

**Comment by vered1986** [comment]
It seems to work well, fixed in https://github.com/vered1986/LexNET/commit/4beb38119bd7bc367154f56e2e16012420959717. Thanks again @yogarshi!
